default: &default
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password: root
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4


production:
  <<: *default
  database: rails_prod


development:
  <<: *default
  database: rails_dev


test:
  <<: *default
  database: rails_test
