production:
  adapter: mysql2
  database: rails_prod
  host: 127.0.0.1
  username: root
  password: root
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4

development:
  adapter: mysql2
  database: rails_dev
  host: 127.0.0.1
  username: root
  password: root
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4

test:
  adapter: mysql2
  database: rails_test
  host: 127.0.0.1
  username: root
  password: root
  # Use "utf8" instead of "utfmb4" for MySQL prior to 5.7.7
  encoding: utf8mb4
